spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user1
    password: 12345
    virtual-host: default

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka/
#      register-with-eureka: true
#      fetch-registry: true
#      registry-fetch-interval-seconds: 3
#  instance:
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 3
#    lease-expiration-duration-in-seconds: 30
