spring:
  application.index: ${spring.application.name}:${HOST:${random.value}}
  cloud:
    config:
      override-system-properties: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://spring-eureka-service1:8761/eureka/,http://spring-eureka-service2:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30
