spring:
  jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false
  cloud:
    stream:
      default-binder: rabbit-cloud-bus
      bindings:
        requestChannel:
          destination: ha.requestExchange
          group: reqQueue
          binder: rabbit-local
          consumer:
            concurrency: 3
        responseChannel:
          destination: ha.responseExchange
          binder: rabbit-local
        errorChannel:
          destination: ha.DLX
          binder: rabbit-local
      binders:
        rabbit-local:
          defaultCandidate: false
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: user2
                password: 12345
                virtual-host: stream
        rabbit-cloud-bus:
          defaultCandidate: false
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: user1
                password: 12345
                virtual-host: default

retry-properties:
  max-attemps: 5
  initial-interval: 1000
  multiplier: 2.0
  max-interval: 60000

